---
title: "Task_2"
author: "Mohsin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the dataset and ggplot2 package.
```{r}
dataset_1 <- read.csv("GlobalLandTemperaturesByCity.csv", header=TRUE, stringsAsFactors=FALSE)
dataset_2 <- read.csv("GlobalLandTemperaturesByCountry.csv", header=TRUE, stringsAsFactors=FALSE)
dataset_3 <- read.csv("GlobalLandTemperaturesByMajorCity.csv", header=TRUE, stringsAsFactors=FALSE)
dataset_4 <- read.csv("GlobalLandTemperaturesByState.csv", header=TRUE, stringsAsFactors=FALSE)
dataset_5 <- read.csv("GlobalTemperatures.csv", header=TRUE, stringsAsFactors=FALSE)
if (!require(ggplot2)) {
  install.packages(ggplot2)
} else {
  library(ggplot2)
}
colnames(dataset_5)[1] = "Year"
dataset_5$Year <- format(as.Date(dataset_5$Year, "%Y-%m-%d"), "%Y")
```

## Line chart showing global temperature change over time
``` {r}
line_chart <- ggplot(dataset_5, aes(x = Year, y = LandAverageTemperature)) +
  geom_line(color = "red") +
  labs(
    title = "Global Temperature Change Over Time",
    x = "Year",
    y = "LandAverageTemperature (°C)"
  ) +
  theme_minimal()

plot(line_chart)
```

## Scatter plot of CO emissions vs. temperature anomaly
``` {r}
scatter_plot <- ggplot(dataset_5, aes(x = LandAverageTemperature, y = LandMaxTemperature)) +
  geom_point(color = "purple") +
  labs(
    title = "LandAverageTemperature vs. LandMaxTemperature",
    x = "LandAverageTemperature",
    y = "LandMaxTemperature"
  ) +
  theme_light()

plot(scatter_plot)
```


## Save the plots as PNG images
``` {r}
ggsave("line_chart.png", plot = line_chart, width = 8, height = 6)
ggsave("scatter_plot.png", plot = scatter_plot, width = 8, height = 6)

cat("Plots saved as 'line_chart.png' and 'scatter_plot.png'")
```
